version: 2.1
jobs:
  build:
    docker:
      - image: docker # the primary container, where your job's commands are run
    steps:
      - setup_remote_docker
      - checkout # check out the code in the project directory
      - run: echo "build image tag $CIRCLE_SHA1"
      - run: docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD cloud.canister.io:5000
      - run: docker build -t cloud.canister.io:5000/msamoht/rtorrent:$CIRCLE_SHA1 -t cloud.canister.io:5000/msamoht/rtorrent:latest .
      - run: docker push cloud.canister.io:5000/msamoht/rtorrent:$CIRCLE_SHA1
      - run: docker push cloud.canister.io:5000/msamoht/rtorrent:latest
